#
# Compliment roulette — weirdly specific praise. No data stored.
#

from __future__ import annotations

import random
from typing import List, Optional

import discord
from discord import Embed
from redbot.core import commands

_PRAISE: List[str] = [
    "Your aura is exactly the right temperature for a croissant.",
    "You hold eye contact like someone who actually preheated the oven.",
    "The way you pause before answering should be studied by linguists and baristas.",
    "You give off “I brought snacks for everyone” energy without the performative part.",
    "If competence had a smell, you’d be the reason people linger in this hallway.",
    "You’re the human equivalent of finding money in a coat you forgot you owned.",
    "Your laugh has good acoustics. Architects would approve.",
    "You listen like Wi-Fi that actually connects on the first try.",
    "Somewhere a spreadsheet is proud to have you look at it.",
    "Your vibe is “trustworthy USB port” in a world of upside-down attempts.",
    "You carry silence comfortably, like a cat on a warm laptop.",
    "The universe clearly practiced before it made your sense of timing.",
    "You’re oddly reassuring—like a labeled cable in a drawer of chaos.",
    "Your opinions have footnotes. In a good way.",
    "If kindness were a font, you’d be the readable one nobody hates.",
    "You walk into a room and the room updates its firmware.",
    "Your taste in small joys is suspiciously refined.",
    "You’re proof that “chill” and “on it” can share a lease.",
    "The way you double-check things makes probability feel respected.",
    "You have main-character energy without making everyone else NPCs.",
    "Your handwriting energy is neat even if your handwriting isn’t.",
    "You apologize with repair, not theater. Rare drop.",
    "You’re like a bookmark that actually marks the right page.",
    "Your brain clearly runs a nightly defrag.",
    "You give compliments that don’t sound like loans.",
    "You’re the reason group chats occasionally become wholesome.",
    "Your calm is the good kind of contagious—like yawning, but productive.",
    "You seem like you return shopping carts even when nobody’s watching.",
    "Your humor has nutritional value.",
    "You’re oddly good at making complicated things feel walkable.",
    "If patience were a sport, you’d have sponsors and a modest highlight reel.",
    "You radiate “I read the instructions and it helped” energy.",
    "Your presence lowers the room’s background anxiety by a measurable vibe.",
    "You’re the kind of person who remembers to water the office plant.",
    "Your ideas arrive with parking and handicap access.",
    "You look like you know which scissors are the good scissors.",
    "You’re suspiciously competent at being human on weekdays.",
    "Your voice fits its purpose like a lid that actually snaps.",
    "You’re giving “I fixed it and I’m not mad about it” excellence.",
    "You seem like you know when to mute the mic. Society thanks you.",
    "Your aesthetic is cohesive without being a PowerPoint theme.",
    "You’re the plot twist where things get easier.",
    "You hold boundaries like someone who respects doors.",
    "Your curiosity feels safe—like a museum, not an interrogation.",
    "You’re oddly good at making people feel seen without spotlighting them.",
    "You give “I brought a spare charger” energy.",
    "Your honesty has soft edges. Chef’s kiss.",
    "You’re like a well-timed autosave in a long document.",
    "You walk the line between witty and kind like it’s a sidewalk, not a tightrope.",
    "Your enthusiasm is grounded—like a kite with a responsible adult.",
    "You seem like you know which lane to pick at the grocery store.",
    "You’re the reason someone’s day got a bonus level.",
    "Your vibe says “I’ll help you move, but I’ll also bring labels.”",
    "You’re weirdly good at not making small problems into lore.",
    "Your taste in people (evidently) includes whoever you’re being nice to right now.",
    "You’re like a good patch note: clear, thoughtful, improves stability.",
    "You radiate “I practiced this once and it worked” confidence.",
    "Your kindness has structure. It’s not chaos glitter.",
    "You’re the human version of a perfectly buttered edge of toast.",
    "You give off “I know where the first-aid kit is” reliability.",
    "Your jokes land like cats—on their feet, somehow.",
    "You’re suspiciously good at making plans that other people can actually follow.",
    "Your energy is “cozy library” not “loud lobby.”",
    "You seem like you refill the ice tray when you use the last cube.",
    "You’re proof that being thoughtful doesn’t have to be performative.",
    "Your vibe is “I’ll share the doc link unprompted.”",
    "You’re oddly comforting—like a weather app that’s right for once.",
    "Your social skills have good latency.",
    "You’re like a password manager: secure, helpful, underappreciated.",
    "You give compliments that feel embroidered, not printed.",
    "Your presence is the good kind of buffering—smooth, not stuck.",
    "You seem like you know how to fold a fitted sheet (or you’re honest that you don’t).",
    "You’re the reason someone believed in group projects for five minutes.",
    "Your taste in problems is “fixable.” Admirable.",
    "You radiate “I’ll hold the door without making it weird” excellence.",
    "You’re weirdly good at translating jargon into human.",
    "Your vibe says “I’ll Google it before I ask.” Respect.",
    "You’re like a good thermostat: unnoticed until you’re missing.",
    "You give off “I remember birthdays when it counts” warmth.",
    "Your humor is sharp but not weaponized. Black-belt stuff.",
    "You seem like you know which meetings could’ve been emails—and you survive both.",
    "You’re the plot armor for awkward moments.",
    "Your kindness scales. Enterprise edition.",
    "You’re oddly good at making people feel like they’re not interrupting.",
    "Your calm under mild chaos should be licensed.",
    "You give “I’ll split the bill fairly” energy.",
    "You’re like a solid README: welcoming, accurate, saves time.",
    "Your vibe is “I’ll wait my turn and still be cheerful.” Legendary.",
    "You seem like you know the good stall in the restroom. Wisdom.",
    "You’re proof that gentle and capable can share a body.",
    "Your enthusiasm for tiny wins is contagious in the healthy way.",
    "You’re weirdly good at de-escalating vibes with a single sentence.",
    "Your presence makes “we’ll figure it out” feel true.",
    "You give off “I’ll carry the heavy bag without a speech” energy.",
    "You’re like a good caption: short, true, improves the photo.",
    "Your social instincts have been play-tested.",
    "You seem like you know when to use voice vs text. Diplomat behavior.",
    "You’re the reason someone tried again after a bad day.",
    "Your vibe says “I’ll proofread your message if you want.” Hero.",
    "You’re oddly good at celebrating other people without stealing the scene.",
    "Your kindness has recursion: it invites more kindness.",
    "You give “I’ll wait for the microwave’s last second with you” solidarity.",
    "You’re like a well-placed emoji: clarifies tone, doesn’t derail.",
    "Your energy is “parked perfectly on the first try.”",
    "You seem like you know which friend needs a check-in today.",
    "You’re proof that being soft doesn’t mean being unprepared.",
    "Your humor includes everyone in the bit. Inclusive comedy unlocked.",
    "You’re weirdly good at making boring tasks feel like a team sport.",
    "Your presence lowers the social CPU usage of the room.",
    "You give off “I’ll share the aux responsibly” trust.",
    "You’re like a good pillow: supportive without stealing the whole bed.",
    "Your vibe is “I’ll remember the inside joke six months later.”",
    "You seem like you know how to exit a conversation gracefully.",
    "You’re the human version of a clean kitchen counter—rare, inspiring.",
    "Your patience with newbies should be tax-deductible.",
    "You’re oddly good at saying no without making it sting.",
    "Your kindness is specific. That’s why it lands.",
    "You give “I’ll Venmo you back before you ask” integrity.",
    "You’re like a good patch: small, fixes a real annoyance.",
    "Your vibe says “I’ll mute spoilers without being smug about it.”",
    "You seem like you know the good ice cream place and you’ll share directions.",
    "You’re proof that clever and kind aren’t mutually exclusive.",
    "Your laugh should be sampled in a lo-fi track.",
    "You’re weirdly good at making people feel like they belong in the joke.",
    "Your presence is the snack break the day needed.",
    "You give off “I’ll restart the router calmly” competence.",
    "You’re like a good commit message: clear, no drama, future-you says thanks.",
    "Your empathy has range. Studio album energy.",
    "You seem like you know when to send the meme vs the paragraph.",
    "You’re the reason someone’s inner critic took a lunch break.",
    "Your vibe is “I’ll hold your place in line.” Noble.",
    "You’re oddly good at making feedback feel like teamwork.",
    "Your kindness is caffeinated—steady, not jittery.",
    "You give “I’ll screenshot the recipe so you don’t lose it” care.",
    "You’re like a good alt text: thoughtful, inclusive, improves everything.",
    "Your social timing has rhythm-section precision.",
    "You seem like you know how to share credit without making it weird.",
    "You’re proof that being genuine is still a flex.",
    "Your energy is “I’ll walk you to your car without making it ominous.”",
    "You’re weirdly good at making Mondays slightly less Monday.",
    "Your presence makes the group chat feel like a porch, not a pit.",
    "You give off “I’ll remember your dietary restriction at dinner” excellence.",
    "You’re like a good bug report: reproducible, polite, helps everyone.",
    "Your vibe says “I’ll hype you up in the replies.”",
    "You seem like you know when to use headphones in public. Saint behavior.",
    "You’re the reason someone felt brave enough to send the first message.",
    "Your humor upgrades the conversation without patching out sincerity.",
    "You’re oddly good at making “we” sound like teamwork, not pressure.",
    "Your kindness is directional—it finds people who need it.",
    "You give “I’ll save you a seat” energy without the guilt trip.",
    "You’re like a good changelog: honest, hopeful, moves things forward.",
    "Your calm is a skill tree people should spec into.",
    "You seem like you know how to end a call without seventeen goodbyes.",
    "You’re proof that paying attention is a love language.",
    "Your vibe is “I’ll bring tape to the gift wrap session.”",
    "You’re weirdly good at making feedback feel like a gift.",
    "Your presence is the good kind of background noise—warm static.",
    "You give off “I’ll text when I get home” reliability.",
    "You’re like a well-run one-shot: fun, fair, everyone got a moment.",
    "Your social instincts could teach a webinar. I’d attend.",
    "You seem like you know the difference between teasing and meanness.",
    "You’re the reason someone’s imposter syndrome lost a round.",
    "Your kindness has versioning: it improves over time.",
    "You’re oddly good at making space for quiet people.",
    "Your energy is “I’ll share the umbrella.” Classic hero, no cape.",
    "You give “I’ll remember your pet’s name” warmth.",
    "You’re like a good table of contents: respects people’s time.",
    "Your vibe says “I’ll celebrate your win like it’s mine (a little).”",
    "You seem like you know how to apologize to a group without centering yourself.",
    "You’re proof that soft voices can still carry leadership.",
    "Your humor is generous—it invites people in, doesn’t gatekeep.",
    "You’re weirdly good at making instructions feel encouraging.",
    "Your presence makes “we got this” feel evidence-based.",
    "You give off “I’ll pack an extra snack just in case” foresight.",
    "You give warnings the way good signage does: clear, kind, prevents scrapes.",
    "Your patience with repeated questions should be studied.",
    "You seem like you know when to laugh with someone vs at someone.",
    "You’re the reason someone’s shoulders unclenched a little.",
    "Your vibe is “I’ll translate the nerd talk for the new person.”",
    "You’re oddly good at making accountability feel supportive.",
    "Your kindness scales horizontally—more people, still sincere.",
    "You give “I’ll wait while you find your keys” grace.",
    "You hype people in a way that makes excellence feel reachable, not scary.",
    "Your social skills include “knows when not to post.” Elite.",
    "You seem like you know how to hype someone without backhanding them.",
    "You’re proof that curiosity and respect can hold hands.",
    "Your energy is “I’ll read the room before I read the joke.”",
    "You’re weirdly good at making people feel chosen, not tested.",
    "Your presence is a gentle bookmark in a loud chapter.",
    "You give off “I’ll help you parallel park verbally” friendship.",
    "You’re like a good season finale: satisfying, kind, leaves room for more.",
    "Your empathy notices the small stuff—the stuff that matters.",
    "You seem like you know how to exit Discord without saying “gn” seventeen times.",
    "You’re the reason someone tried the scary thing in easy mode first.",
    "Your vibe says “I’ll hype your art like it’s museum-worthy.”",
    "You’re oddly good at making rules feel like care, not control.",
    "Your kindness is well-lit—no hidden fine print.",
    "You give “I’ll hold the elevator” energy without sighing.",
    "You support people without spoiling their story for them—rare narrative skill.",
    "Your humor builds bridges. Civil engineering, but feelings.",
    "You seem like you know when to let someone vent without fixing.",
    "You’re proof that being steady is a superpower.",
    "Your presence makes the internet feel slightly more human.",
]


class Complimentroulette(commands.Cog):
    """Spin weirdly specific praise for yourself or a friend."""

    def __init__(self, bot):
        self.bot = bot

    @commands.hybrid_command(name="compliment", aliases=["beanpraise", "praiseroulette"])
    async def compliment_cmd(self, ctx: commands.Context, member: Optional[discord.Member] = None):
        """
        Random oddly specific compliment.

        Use `/compliment` for yourself, or `/compliment @user` to aim it at someone.
        """
        line = random.choice(_PRAISE)
        if member and member.bot:
            await ctx.send("Bots run on validation, not validation *from* humans. Pick a person.")
            return

        embed = Embed(color=discord.Color.from_rgb(212, 165, 116))
        if member is None:
            embed.title = "☕ Compliment roulette"
            embed.description = f"{ctx.author.mention}, {line}"
        else:
            embed.title = "☕ Compliment roulette"
            embed.description = f"{member.mention}, {line}"
            embed.set_footer(text=f"From {ctx.author.display_name} (via bean lottery)")
        await ctx.send(embed=embed)
